//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendCorp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaPr
    {
        public int ID { get; set; }
        public string BarCode { get; set; }
        public string PartNo { get; set; }
        public string Descr { get; set; }
        public string DescrCN { get; set; }
        public string PicFileName { get; set; }
        public string CPartNo { get; set; }
        public string Species { get; set; }
        public string ISize { get; set; }
        public string ColorKind { get; set; }
        public string Plating { get; set; }
        public string Material { get; set; }
        public string IShape { get; set; }
        public Nullable<decimal> MaterialExp { get; set; }
        public string StoneCode { get; set; }
        public string StoneSize { get; set; }
        public string StoneShape { get; set; }
        public Nullable<decimal> StoneQtys { get; set; }
        public Nullable<decimal> WasteRate { get; set; }
        public Nullable<decimal> HumanExp { get; set; }
        public Nullable<decimal> CostZm { get; set; }
        public Nullable<decimal> CostPg { get; set; }
        public Nullable<decimal> CostDd { get; set; }
        public string LevelZm { get; set; }
        public string IUnit { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightMemo { get; set; }
        public string INote { get; set; }
        public string EditMemo { get; set; }
        public string ModelNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CheckPriceDt { get; set; }
        public Nullable<decimal> SilverWeight { get; set; }
        public Nullable<System.DateTime> EditDateDd { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string CreateEmployeeCode { get; set; }
        public string EditEmployeeCode { get; set; }
        public string MadeSupply { get; set; }
        public Nullable<decimal> SilverLoss { get; set; }
        public Nullable<decimal> SettingCost { get; set; }
        public Nullable<decimal> PolishingCost { get; set; }
        public Nullable<decimal> MountingCost { get; set; }
        public Nullable<decimal> PlatingCost { get; set; }
        public Nullable<decimal> StoneCost { get; set; }
        public Nullable<decimal> TotalProngs { get; set; }
        public Nullable<decimal> LoppingCost { get; set; }
        public Nullable<decimal> CostST { get; set; }
        public Nullable<decimal> CostPA { get; set; }
        public Nullable<decimal> CostDM { get; set; }
        public Nullable<decimal> CostXS { get; set; }
        public Nullable<decimal> CostNS { get; set; }
        public Nullable<decimal> CostSH { get; set; }
        public Nullable<decimal> CostOT { get; set; }
        public string CostRemark { get; set; }
        public Nullable<System.DateTime> CostCrDate { get; set; }
        public Nullable<System.DateTime> CostEdDate { get; set; }
        public string CostCrEmpCode { get; set; }
        public string CostEdEmpCode { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> WeightCS { get; set; }
        public Nullable<decimal> WeightPA { get; set; }
        public Nullable<decimal> WeightST { get; set; }
        public Nullable<System.DateTime> CreatePriceDt { get; set; }
        public Nullable<decimal> UnitPrice08 { get; set; }
        public string NoMemo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckEmployeeCode { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<decimal> WorkPriceZM { get; set; }
        public Nullable<decimal> WorkPricePG { get; set; }
        public Nullable<System.DateTime> WorkPriceCheckDt { get; set; }
        public string QuNoZm { get; set; }
        public string QuNoPg { get; set; }
        public string SetNo1 { get; set; }
        public string SetNo2 { get; set; }
        public string SetNo3 { get; set; }
        public Nullable<bool> NeedNewPic { get; set; }
        public string BarCodeS1 { get; set; }
        public string BarCodeS2 { get; set; }
        public string BarCodeS3 { get; set; }
        public Nullable<decimal> GoldWeight { get; set; }
        public string Descr2 { get; set; }
    }
}
